@extends('front')
@section('title')
Privacy policy
@stop
@section('content')
<h2 class="icon-court title">Legal</h2>

<div class="content">
<h2 class="titles">Politica de privacidad y tratamiento de datos</h2>

<p>Refill24 SL, asume de manera activa y comprometida el cumplimiento de la normativa sobre protección de datos personales.</p>
<p>El usuario, al facilitar la información requerida o datos de carácter personal, está aceptando su tratamiento y/o comunicación en la forma contemplada en esta Política sobre Tratamiento de Datos Personales. Si el Usuario no estuviera de acuerdo con alguno de los extremos aquí regulados, deberá abstenerse de introducir información de carácter personal a través de la página web.</p>
<p>Refill24 SL, como responsable de los datos recabados a través de esta página web, ha implantado en sus sistemas informáticos e instalaciones las medidas técnicas y organizativas necesarias para garantizar su confidencialidad y evitar su alteración, pérdida, tratamiento y/o acceso no autorizado. Asimismo, Refill24 , SL ha procedido a la inscripción de los correspondientes ficheros en la Agencia Española de Protección de Datos.</p>
<p>El usuario autoriza a Refill24 el tratamiento de los datos personales que suministre para su utilización con fines promocionales, informativos y estadísticos. Además de la información facilitada puede tratarse la dirección IP con el fin de identificar el terminal desde el cual se introduce la información y obtener la ubicación geográfica del usuario.</p>
<p>El usuario consiente expresamente el envío de comunicaciones comerciales -por correo electrónico, correo postal o teléfono- por parte de Refill24 SL, para hacerle llegar ofertas o comunicaciones publicitarias que puedan ser de su interés relativas al en el que Refill24 desarrolla su actividad (comercialización de consumibles y material informático, recarga de cartuchos y franquicia de negocios en este sector).</p>
<p>Este sitio mide el tráfico utilizando la solución Google Analytics, un servicio analítico de web prestado por Google, Inc., una compañía de Delaware cuya oficina principal está en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos (“Google”). Google Analytics utiliza “cookies”, que son archivos de texto ubicados en el ordenador del usuario, para ayudar al website a analizar el uso que hacen los usuarios del sitio web. La información que genera la cookie acerca del uso del website (incluyendo la dirección IP de los usuarios o visitantes) será directamente transmitida y archivada por Google en los servidores de Estados Unidos. Google usará esta información por cuenta nuestra con el propósito de hacer el seguimiento del uso del website, recopilando informes de la actividad del website y prestando otros servicios relacionados con la actividad del website y el uso de Internet. Google podrá transmitir dicha información a terceros cuando así se lo requiera la legislación, o cuando dichos terceros procesen la información por cuenta de Google. Google no asociará la dirección IP de los usuarios con ningún otro dato del que disponga Google. El usuario puede rechazar el tratamiento de los datos o la información rechazando el uso de cookies mediante la selección de la configuración apropiada del navegador, sin embargo, en tal caso puede ser que no se pueda usar la plena funcionabilidad de este website. Al acceder a esta página el usuario consiente el tratamiento de la citada información por Google en la forma y para los fines indicados. El usuario puede ver más información sobre la política de privacidad de Google Analytics en <a target="_blank" href="http://www.google.com/intl/es_ALL/privacypolicy.html" title="Política de Privacidad de Google Analytics">Política de Privacidad de Google Analytics</a>.</p>
<p>Refill24 pretende no recabar dato personal alguno perteneciente a personas menores de catorce años de edad. Si este es tu caso, no nos facilites ningún dato personal.</p>
<p>El usuario puede ejercitar sus derechos de acceso, rectificación, oposición y cancelación mediante comunicación escrita, adjuntando fotocopia de su DNI, dirigida a Refill24 (responsable del fichero), Av. Archiduque Carlos, 125 bajo, 46014 Valencia, o bien mediante correo electrónico dirigido a la siguiente dirección: info@refill24.es</p>
<p>Asimismo, el usuario podrá revocar en cualquier momento el consentimiento prestado para el tratamiento de sus datos utilizando para ello cualquiera de los dos medios expresados.</p>
</div>
@stop